import matplotlib.pyplot as plt
import numpy as np

dqn = np.load('dqn_500.npy')
# dqn_rewardmodel = np.load('data_dqn_rewardmodel_3.npy')
dqn_rewardmodel_2 = np.load('v2_metarewardmodel_500.npy')
# dqn_pri = np.load('666_500.npy')
dqn_pbsr = np.load('PBRS_500.npy')
# print(dqn[-1] - dqn[-2])
# # print(dqn_rewardmodel[-1] - dqn_rewardmodel[-2])
# print(dqn_rewardmodel_2[-1] - dqn_rewardmodel_2[-2])
# print(dqn_pri[-1] - dqn_pri[-2])
# print(dqn_rewardmodel)
# dqn_rewardmodel10 = np.load('data_dqn_rewardmodel_10.npy')
plt.plot(range(len(dqn)), dqn, label='conventional DQN')
# plt.plot(range(len(dqn_rewardmodel)), dqn_rewardmodel, c='green', label='DQN with reward model')
# plt.plot(range(len(dqn_pri)), dqn_pri, c='orange', label='DQN with prioritized replay meta')
plt.plot(range(len(dqn_pbsr)), dqn_pbsr, label='DQN with PBSR')
plt.plot(range(len(dqn_rewardmodel_2)), dqn_rewardmodel_2, c='r', label='DQN with meta reward model')
plt.legend(loc='best')
plt.ylabel('total training time')
plt.xlabel('episode')
# plt.grid()
plt.show()
